@startuml

R.P.R.O -r-> Acronym
Acronym -d-> " R "
Acronym -d-> P
Acronym -d-> R
Acronym -d-> O
" R " --> Retrospective
P --> Personality
R --> Recovery
O --> Organization
Retrospective -d-> Meaning
Personality -d-> Meaning
Recovery -d-> Meaning
Organization -d-> Meaning
Meaning -r-> Retrospective Personality Recovery Organization

@enduml
