@startuml

left to right direction
'top to bottom direction

rectangle GitHub
rectangle Archive
rectangle "Newgrounds Archive"
rectangle "SoundCloud Archive"

GitHub --> Archive 
Archive --> "Newgrounds Archive"
Archive --> "Soundcloud Archive"
"Newgrounds Archive" --> "SoundCloud Archive"

@enduml
