@startuml

left to right direction
'top to bottom direction

rectangle GitHub
circle Archive
rectangle "Newgrounds Archive"
rectangle "SoundCloud Archive"

GitHub --> Archive : Our Hosting Servers 
Archive --> (Newgrounds Archive)
Archive --> (SoundCloud Archive)
(Newgrounds Archive) --> (SoundCloud Archive) : Link from Newgrounds

@enduml
